FROM jeongukjae/python-mecab-ko:3.7-slim

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
COPY ./requirements .

RUN pip install -r prod.txt

COPY . .